# Generated by Django 3.1.7 on 2021-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210429_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
